### ISSUE TITLE
2019でアップロードできません

### ISSUE THREAD

**Issue by spica1476** [ahzkwid/BoothSupport#10]
![e1](https://github.com/ahzkwid/BoothSupport/assets/168617889/2f73938a-0567-4860-8da5-7c4203c151ea)
![e2](https://github.com/ahzkwid/BoothSupport/assets/168617889/c33e2cf9-2030-4663-9c6c-cd2d4f5a1487)
![e3](https://github.com/ahzkwid/BoothSupport/assets/168617889/8c1e356c-350c-48c5-af2a-0108c0d9b99f)

買ったそのままなのに何もできません

**Comment by ahzkwid** [comment]
ごめんなさい。このメッセージを今見つけました。

**Comment by ahzkwid** [comment]
問題を再確認するためにオープンしました

**Comment by ahzkwid** [comment]
v1.4.1として把握されます

**Comment by ahzkwid** [comment]
![image](https://github.com/ahzkwid/BoothSupport/assets/64906101/a831b24b-06ce-41e9-91dd-c64f99c5e57f)
2022.3.6f1で合格しました。 エラーメッセージを見ると2019.4.31f1問題と推測されます

**Comment by ahzkwid** [comment]
![image](https://github.com/ahzkwid/BoothSupport/assets/64906101/9e338cd5-3343-4294-9acf-3066a46f953a)
2019.4.31f1で確認しました。

**Comment by ahzkwid** [comment]
![image](https://github.com/ahzkwid/BoothSupport/assets/64906101/ce75fdfb-4926-4823-8624-9c89a01a9fba)
解決しました。 v1.6.0 で新機能とともに配布される予定です。 ファイル配布後に閉じます。

**Comment by ahzkwid** [comment]
アップデート完了
913666cb86148003e4ccc4ab0c16121ac46e97c6
