### ISSUE TITLE
特定のワールドでアバターに透明な膜のようなものが被せられます

### ISSUE THREAD

**Issue by YeonSpring** [ahzkwid/BoothSupport#11]
![123123](https://github.com/ahzkwid/BoothSupport/assets/170391523/926df6b4-b4c5-4833-8257-b99996686317)

この写真のように膜が被せられます

**Comment by ahzkwid** [comment]
確認しました。すぐ対応します。

**Comment by YeonSpring** [comment]
早い対応ありがとうございます！

**Comment by ahzkwid** [comment]
ワルドの名前を教えてくれたら、対応がもっと良くなります

**Comment by YeonSpring** [comment]
ワールドの名前はOpal Bayです
念のためリンクも一緒に送ります
https://vrchat.com/home/world/wrld_eca2ddde-f794-4c59-ae3a-4dd5881eb18b
どうもよろしくお願いします

**Comment by ahzkwid** [comment]
![image](https://github.com/ahzkwid/BoothSupport/assets/64906101/09da9d2c-c058-4e5e-90cd-00efffd3e6e7)
原因

**Comment by ahzkwid** [comment]
![image](https://github.com/ahzkwid/BoothSupport/assets/64906101/cb99bfc6-57e8-41e4-b9bb-a8f6d61ca094)
リペアツールの作成

**Comment by ahzkwid** [comment]
![VRChat_2024-05-21_17-29-01 167_1920x1080](https://github.com/ahzkwid/BoothSupport/assets/64906101/d5747009-f356-45e2-a4d0-f0f306c4e14d)
前
![VRChat_2024-05-21_18-08-38 869_1920x1080](https://github.com/ahzkwid/BoothSupport/assets/64906101/97ea72bd-ba31-49c5-90d5-70782802f6ab)
後

修正完了

**Comment by ahzkwid** [comment]
armatureの変更により、MAテストも進行します。

**Comment by YeonSpring** [comment]
ありがとうございます
お疲れ様でしたー
