### ISSUE TITLE
MYAトレーナーセットについている帽子が...

### ISSUE THREAD

**Issue by ferret031** [ahzkwid/BoothSupport#16]
Milkトレーナーセットを購入したいのですが、MYAトレーナーセットに付属している帽子のデザインが大好きで、それもお付けしていただくことは可能でしょうか。。。？

**Comment by ahzkwid** [comment]
ご要望ありがとうございます。
12月まで予定があるので、12月以降に改めて見直したいと思います。
追加作業を進める場合、公平性のためにまめひなたとキプフェルの他にクララとコロネも進行しなければならないため大型作業になります。

**Comment by ahzkwid** [comment]
1月まで追加予定があるため、延期させていただきます。
すべてのスケジュールが終了次第、検討する意向はございますが、優先度は低めでございます。
何卒ご了承くださいませ。
